Add hd=toptal.com parameter
toptal/traefik-forward-auth pull request #3
Opened 2021-10-19 21:24 UTC by GuilhermeBarile

This parameter instructs google to use the toptal.com account present in the user session

2021-10-19 21:25 UTC, GuilhermeBarile commented
@jondoveston should we parameterize this?

2021-10-19 21:28 UTC, Galathius approved these changes

2021-10-20 20:14 UTC, jondoveston approved these changes

2021-10-20 20:17 UTC, jondoveston requested changes
Yes I think this would be better as a parameter.

2021-11-01 13:53 UTC, GuilhermeBarile commented
:+1:

2021-11-01 13:54 UTC, merged